---
- name: Install and start Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      when: ansbile_distribution == 'Ubuntu"

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Create Content
      copy:
        content: "Hello, Welcome"
        dest: /var/www/html/index.html
